# Generated by Django 2.2.6 on 2020-02-11 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guessnumbers',
            old_name='test',
            new_name='text',
        ),
    ]
